function run_physics_validation(results_dir, params, h2case, env, pipe)
%RUN_PHYSICS_VALIDATION Export sanity checks for the physical layer.

nPipe = h2case.pipeline.count;
T = params.meta.T;

rows = {};
for l = 1:nPipe
    rows{end+1,1} = { ...
        string(h2case.pipeline.names(l)), ...
        min(pipe.temperature_inlet_k(l,:) - 273.15), max(pipe.temperature_inlet_k(l,:) - 273.15), ...
        min(pipe.temperature_outlet_k(l,:) - 273.15), max(pipe.temperature_outlet_k(l,:) - 273.15), ...
        min(pipe.temperature_gas_k(l,:) - 273.15), max(pipe.temperature_gas_k(l,:) - 273.15), ...
        min(pipe.heat_exchange_chi(l,:)), max(pipe.heat_exchange_chi(l,:)), ...
        min(env.theta_seabed_c(l,:)), max(env.theta_seabed_c(l,:)), ...
        min(pipe.Z(l,:)), max(pipe.Z(l,:)), ...
        min(pipe.viscosity_pa_s(l,:)), max(pipe.viscosity_pa_s(l,:)), ...
        min(pipe.reynolds(l,:)), max(pipe.reynolds(l,:)), ...
        min(pipe.friction_factor(l,:)), max(pipe.friction_factor(l,:)), ...
        min(pipe.limit_dynamic_kg_h(l,:)), max(pipe.limit_dynamic_kg_h(l,:)), ...
        pipe.limit_static_kg_h(l)}; %#ok<AGROW>
end

summary = cell2table(vertcat(rows{:}), 'VariableNames', { ...
    'pipeline', 'Tin_min_c', 'Tin_max_c', 'Tout_min_c', 'Tout_max_c', ...
    'Tgas_min_c', 'Tgas_max_c', 'chi_min', 'chi_max', ...
    'theta_min_c', 'theta_max_c', 'Z_min', 'Z_max', ...
    'mu_min_pa_s', 'mu_max_pa_s', 'Re_min', 'Re_max', ...
    'f_min', 'f_max', 'limit_min_kg_h', 'limit_max_kg_h', ...
    'static_limit_kg_h'});
writetable(summary, fullfile(results_dir, 'physics_validation_summary.csv'));

hourly = table((0:T-1).', 'VariableNames', {'hour'});
for l = 1:nPipe
    hourly.(sprintf('pipe%d_Tin_c', l)) = pipe.temperature_inlet_k(l,:).' - 273.15;
    hourly.(sprintf('pipe%d_Tout_c', l)) = pipe.temperature_outlet_k(l,:).' - 273.15;
    hourly.(sprintf('pipe%d_Tgas_avg_c', l)) = pipe.temperature_gas_k(l,:).' - 273.15;
    hourly.(sprintf('pipe%d_chi', l)) = pipe.heat_exchange_chi(l,:).';
    hourly.(sprintf('pipe%d_theta_c', l)) = env.theta_seabed_c(l,:).';
    hourly.(sprintf('pipe%d_Z', l)) = pipe.Z(l,:).';
    hourly.(sprintf('pipe%d_Re', l)) = pipe.reynolds(l,:).';
    hourly.(sprintf('pipe%d_f', l)) = pipe.friction_factor(l,:).';
    hourly.(sprintf('pipe%d_limit_kg_h', l)) = pipe.limit_dynamic_kg_h(l,:).';
end
writetable(hourly, fullfile(results_dir, 'physics_validation_hourly.csv'));

assert(all(pipe.Z(:) > 0.8 & pipe.Z(:) < 1.5), 'Unexpected PR Z range.');
assert(all(pipe.viscosity_pa_s(:) > 5e-6 & pipe.viscosity_pa_s(:) < 2e-5), ...
    'Unexpected hydrogen viscosity range.');
assert(all(pipe.friction_factor(:) > params.range.friction_factor(1) & ...
    pipe.friction_factor(:) < params.range.friction_factor(2)), ...
    'Unexpected Darcy friction factor range.');
assert(all(pipe.limit_dynamic_kg_h(:) > 0), 'Pipeline capacity must be positive.');

end
